{{- if .Values.app.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Values.app.name }}-ingress
  namespace: {{ .Values.namespace.name }}
  annotations:
    {{- range $key, $value := .Values.app.ingress.annotations }}
    {{ $key }}: {{ $value | quote }}
    {{- end }}
spec:
  ingressClassName: {{ .Values.app.ingress.className }}
  rules:
  {{- range .Values.app.ingress.hosts }}
  - host: {{ .host }}
    http:
      paths:
      {{- range .paths }}
      - path: {{ .path }}
        pathType: {{ .pathType }}
        backend:
          service:
            name: {{ $.Values.app.name }}
            port:
              number: {{ $.Values.app.service.port }}
      {{- end }}
  {{- end }}
  {{- if .Values.app.ingress.tls }}
  tls:
    {{- toYaml .Values.app.ingress.tls | nindent 4 }}
  {{- end }}
{{- end }}
