apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.app.name }}
  namespace: {{ .Values.namespace.name }}
  labels:
    app: {{ .Values.app.name }}
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "{{ .Values.app.env.port }}"
    prometheus.io/path: "/metrics"
spec:
  type: {{ .Values.app.service.type }}
  ports:
  - port: {{ .Values.app.service.port }}
    targetPort: {{ .Values.app.env.port }}
    protocol: TCP
    name: http
  selector:
    app: {{ .Values.app.name }}
---
{{- if .Values.app.loadBalancer.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.app.name }}-lb
  namespace: {{ .Values.namespace.name }}
  labels:
    app: {{ .Values.app.name }}
spec:
  type: LoadBalancer
  ports:
  - port: {{ .Values.app.loadBalancer.port }}
    targetPort: {{ .Values.app.loadBalancer.targetPort }}
    protocol: TCP
    name: http
  selector:
    app: {{ .Values.app.name }}
{{- end }}
