---
apiVersion: v1
kind: Secret
metadata:
  name: mongodb-auth
  namespace: kubedb-dbaas
type: Opaque
stringData:
  username: mongodb
  password: mongodb123!@#
---
apiVersion: kubedb.com/v1alpha2
kind: MongoDB
metadata:
  name: kubedb-dbaas-mongodb
  namespace: kubedb-dbaas
spec:
  version: "7.0.8"
  replicas: 3
  replicaSet:
    name: rs0
  storage:
    storageClassName: "ckp-storage"
    accessModes:
      - ReadWriteOnce
    resources:
      requests:
        storage: 10Gi
  terminationPolicy: WipeOut
  authSecret:
    name: mongodb-auth
  podTemplate:
    spec:
      resources:
        requests:
          cpu: "500m"
          memory: "1Gi"
        limits:
          cpu: "1000m"
          memory: "2Gi"
---
apiVersion: v1
kind: Service
metadata:
  name: mongodb
  namespace: kubedb-dbaas
spec:
  selector:
    app.kubernetes.io/name: mongodbs.kubedb.com
    app.kubernetes.io/instance: kubedb-dbaas-mongodb
  ports:
    - name: mongodb
      port: 27017
      targetPort: 27017
  type: ClusterIP
