---
apiVersion: v1
kind: Secret
metadata:
  name: redis-auth
  namespace: kubedb-dbaas
type: Opaque
stringData:
  password: redis123!@#
---
apiVersion: kubedb.com/v1alpha2
kind: Redis
metadata:
  name: kubedb-dbaas-redis
  namespace: kubedb-dbaas
spec:
  version: "7.2.4"
  mode: Standalone
  storage:
    storageClassName: "ckp-storage"
    accessModes:
      - ReadWriteOnce
    resources:
      requests:
        storage: 5Gi
  terminationPolicy: WipeOut
  authSecret:
    name: redis-auth
  podTemplate:
    spec:
      resources:
        requests:
          cpu: "250m"
          memory: "512Mi"
        limits:
          cpu: "500m"
          memory: "1Gi"
---
apiVersion: v1
kind: Service
metadata:
  name: redis
  namespace: kubedb-dbaas
spec:
  selector:
    app.kubernetes.io/name: redises.kubedb.com
    app.kubernetes.io/instance: kubedb-dbaas-redis
  ports:
    - name: redis
      port: 6379
      targetPort: 6379
  type: ClusterIP
